

apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node
spec:
  ports:
  - name: node
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node
  type: LoadBalancer
status:
  loadBalancer: {}
